if(WIN32)
	find_path(Glslang_Parent_DIR
		NAMES "glslang/CMakeLists.txt"
		PATHS "$ENV{VULKAN_SDK}")
else()
	find_path(Glslang_Parent_DIR
		NAMES "glslang/CMakeLists.txt"
		PATHS "$ENV{VULKAN_SDK}/../source")
endif()

if (NOT Glslang_Parent_DIR STREQUAL "Glslang_Parent_DIR-NOTFOUND")
	set(ENABLE_GLSLANG_BINARIES FALSE CACHE BOOL "")
	set(ENABLE_HLSL FALSE CACHE BOOL "")
	set(ENABLE_OPT FALSE CACHE BOOL "")
	set(ENABLE_PCH FALSE CACHE BOOL "")
	set(ENABLE_SPVREMAPPER FALSE CACHE BOOL "")
	set(SKIP_GLSLANG_INSTALL ON CACHE INTERNAL "" FORCE)
	set(BUILD_TESTING OFF CACHE INTERNAL "" FORCE)
	set(SKIP_SPIRV_TOOLS_INSTALL ON CACHE INTERNAL "" FORCE)
	set(SPIRV_SKIP_EXECUTABLES ON CACHE INTERNAL "" FORCE)
	add_subdirectory("${Glslang_Parent_DIR}/glslang" "${CMAKE_CURRENT_BINARY_DIR}/glslang")
endif()
